
def lan_dict(lan,value)
    d = { 
        eng:{
            "Your Cart": "Your Cart",
            "Cart": "Cart",
            "Product": "Product",
            "Price": "Price",
            "Sub Total": "Sub Total",
            "Qty": "Qty",
            "Payment": "Payment",
            "Subtotal": "Subtotal",
            "Shipping": "Shipping",
            "Total": "Total",
            "Choose Payment Method": "Choose Payment Method",
            "Business Credit": "Business Credit",
            "Credit Card": "Credit Card",
            "Checkout": "Checkout",
            "Letter Paper": "Letter Paper",
            "Legal Paper": "Legal Paper",
            "Settings": "Settings",
            "Offline Order": "Offline Order",
            "Get a Corporate Account": "Get a Corporate Account",
            "Sign In": "Sign In",
            "Link Account with Apruve": "Link Account with Apruve",
            "Signed in as": "Signed in as",
            "24_ream": "24 lb ream (250 Sheets). <br> Paper dimensions 8.5 x 14.00 inches",
            "20_ream": "20 lb ream (500 Sheets). <br>Paper dimensions 8.5 x 11.00 inches",
            "Change Banner": "Change Banner",
            "Upload Logo": "Upload Logo",
            "Language Preference": "Language Preference",
            "Save": "Save",
            "Upload": "Upload",
            "Chinese": "Chinese",
            "Sign in to your account": "Sign in to your account",
            "Email": "Email",
            "Password": "Password" 

        },
        zh:{
            "Your Cart": "您的购物车",
            "Cart": "购物车",
            "Product": "购物清单",
            "Price": "单价",
            "Sub Total": "小计(美金)",
            "Qty": "数量",
            "Payment": "结算",
            "Subtotal": "小计",
            "Shipping": "运费",
            "Total": "总计",
            "Choose Payment Method": "请选择付款方式",
            "Business Credit": "商业信用",
            "Credit Card": "信用卡",
            "Checkout": "付款",
            "Letter Paper": "A4复印纸",
            "Legal Paper": "多功能打印纸",
            "Settings": "设置",
            "Offline Order": "线下订单",
            "Get a Corporate Account": "获得企业账号",
            "Sign In": "登陆",
            "Link Account with Apruve": "将账号与Apruve关联",
            "Signed in as": "您已登陆为",
            "24_ream": "24磅，令(250 张纸). <br> 纸张尺寸 8.5 x 14.00 英尺",
            "20_ream": "20磅 令(500 张纸). <br> 纸张尺寸 8.5 x 11.00 英尺",
            "Change Banner": "编辑横幅",
            "Upload Logo": "上传标识",
            "Language Preference": "选择语言",
            "Save": "保存",
            "Upload": "上传",
            "Chinese": "中文",
            "Sign in to your account": "登陆您的账号",
            "Email": "电子邮箱",
            "Password": "密码"   
        }
    } 
    return d[@@language][value]
end


