source 'https://rubygems.org'

ruby '2.6.7'
gem 'rack', '>= 2.0.6'
gem 'sinatra', '~> 2.0.2'
gem 'shotgun'
gem 'thin'
gem 'activemodel'
gem 'coffee-script'
gem 'json', '>= 1.8.3'
gem 'rack-flash3'
gem 'apruve'
gem 'dotenv'
gem 'oauth2'
gem 'money'
gem 'sinatra-flash'
gem 'aws-s3'
gem 'aws-sdk', '~> 2.0.22'

group :test do
  gem 'rspec'
  gem 'shoulda-matchers'
  gem 'shoulda'
  gem 'rack-test'
end
